import { CardKind, CardRank, HeroKind } from "@/types";
import HeroicStrike from '@/assets/servants/1.png';
import Whirlwind from '@/assets/servants/2.png';
import Charge from '@/assets/servants/3.png';

import KingMosh from '@/assets/servants/4.png';
import Backstab from '@/assets/servants/5.png';
import Assassinate from '@/assets/servants/6.png';
import Betrayal from '@/assets/servants/7.png';
import Eviscerate from '@/assets/servants/8.png';
import EdwinVanCleef from '@/assets/servants/9.png';
import GoldshireFootman from '@/assets/servants/10.png';
import SenjinShieldmasta from '@/assets/servants/11.png';
import FrostwolfGrunt from '@/assets/servants/12.png';
import FenCreeper from '@/assets/servants/13.png';
import Spellbreaker from '@/assets/servants/14.png';
import AcidicSwampOoze from '@/assets/servants/15.png';
import Nightblade from '@/assets/servants/16.png';
import EarthenRingFarseer from '@/assets/servants/17.png';
import VoodooDoctor from '@/assets/servants/18.png';
import ShatteredSunCleric from '@/assets/servants/19.png';
import PriestessOfElune from '@/assets/servants/20.png';
import DarkscaleHealer from '@/assets/servants/21.png';
import DarkIronDwarf from '@/assets/servants/22.png';
import ElvenArcher from '@/assets/servants/23.png';
import FrostwolfWarlord from '@/assets/servants/24.png';
import Gorehowl from '@/assets/servants/25.png';

type CardAttr = {
  image: string;
  cost: number;
  name: string;
  hp: number;
  attack: number;
  trait: 0 | 3;
  canAttack: number;
  needTarget: boolean;
  type: 'servant' | 'magic' | 'weapon' | 'none';
  class: HeroKind;
  rank: CardRank;
}

export const CardAttrs: Record<CardKind, CardAttr> = {
  [CardKind.None]: {
    image: '',
    cost: 0,
    name: '',
    hp: 0,
    attack: 0,
    trait: 0,
    canAttack: 0,
    needTarget: false,
    type: 'none',
    class: HeroKind.None,
    rank: CardRank.N,
  },
  [CardKind.HeroicStrike]: {
    image: HeroicStrike,
    cost: 2,
    name: 'Heroic Strike',
    hp: 0,
    attack: 0,
    trait: 0,
    canAttack: 0,
    needTarget: false,
    type: 'magic',
    class: HeroKind.Warrior,
    rank: CardRank.N,
  },
  [CardKind.Whirlwind]: {
    image: Whirlwind,
    cost: 1,
    name: 'Whirlwind',
    hp: 0,
    attack: 0,
    trait: 0,
    canAttack: 0,
    needTarget: false,
    type: 'magic',
    class: HeroKind.Warrior,
    rank: CardRank.N,
  },
  [CardKind.Charge]: {
    image: Charge,
    cost: 3,
    name: 'Charge',
    hp: 0,
    attack: 0,
    trait: 0,
    canAttack: 0,
    needTarget: true,
    type: 'magic',
    class: HeroKind.Warrior,
    rank: CardRank.N,
  },
  [CardKind.KingMosh]: {
    image: KingMosh,
    cost: 7,
    name: 'Dragon Roar',
    hp: 6,
    attack: 7,
    trait: 0,
    canAttack: 0,
    needTarget: false,
    type: 'servant',
    class: HeroKind.Warrior,
    rank: CardRank.SSR,
  },
  [CardKind.Backstab]: {
    image: Backstab,
    cost: 0,
    name: 'Shadowstrike',
    hp: 0,
    attack: 0,
    trait: 0,
    canAttack: 0,
    needTarget: true,
    type: 'magic',
    class: HeroKind.Rogue,
    rank: CardRank.N,
  },
  [CardKind.Assassinate]: {
    image: Assassinate,
    cost: 5,
    name: 'Thrust',
    hp: 0,
    attack: 0,
    trait: 0,
    canAttack: 0,
    needTarget: true,
    type: 'magic',
    class: HeroKind.Rogue,
    rank: CardRank.R,
  },
  [CardKind.Betrayal]: {
    image: Betrayal,
    cost: 2,
    name: 'Betrayal of the Fallen',
    hp: 0,
    attack: 0,
    trait: 0,
    canAttack: 0,
    needTarget: true,
    type: 'magic',
    class: HeroKind.Rogue,
    rank: CardRank.N,
  },
  [CardKind.Eviscerate]: {
    image: Eviscerate,
    cost: 2,
    name: 'Sustained Assault',
    hp: 0,
    attack: 0,
    trait: 0,
    canAttack: 0,
    needTarget: true,
    type: 'magic',
    class: HeroKind.Rogue,
    rank: CardRank.N,
  },
  [CardKind.EdwinVanCleef]: {
    image: EdwinVanCleef,
    cost: 3,
    name: 'Duke Nicholas',
    hp: 2,
    attack: 2,
    trait: 0,
    canAttack: 0,
    needTarget: false,
    type: 'servant',
    class: HeroKind.Rogue,
    rank: CardRank.SSR,
  },
  [CardKind.GoldshireFootman]: {
    image: GoldshireFootman,
    cost: 1,
    name: 'Taunter',
    hp: 2,
    attack: 1,
    trait: 3,
    canAttack: 0,
    needTarget: false,
    type: 'servant',
    class: HeroKind.None,
    rank: CardRank.N,
  },
  [CardKind.SenjinShieldmasta]: {
    image: SenjinShieldmasta,
    cost: 4,
    name: 'Ridiculer',
    hp: 5,
    attack: 3,
    trait: 3,
    canAttack: 0,
    needTarget: false,
    type: 'servant',
    class: HeroKind.None,
    rank: CardRank.N,
  },
  [CardKind.FrostwolfGrunt]: {
    image: FrostwolfGrunt,
    cost: 2,
    name: 'Light Cavalry',
    hp: 2,
    attack: 2,
    trait: 3,
    canAttack: 0,
    needTarget: false,
    type: 'servant',
    class: HeroKind.None,
    rank: CardRank.N,
  },
  [CardKind.FenCreeper]: {
    image: FenCreeper,
    cost: 5,
    name: 'Forest Wayfarer',
    hp: 6,
    attack: 3,
    trait: 3,
    canAttack: 0,
    needTarget: false,
    type: 'servant',
    class: HeroKind.None,
    rank: CardRank.N,
  },
  [CardKind.Spellbreaker]: {
    image: Spellbreaker,
    cost: 4,
    name: 'Annihilator',
    hp: 3,
    attack: 4,
    trait: 0,
    canAttack: 0,
    needTarget: true,
    type: 'servant',
    class: HeroKind.None,
    rank: CardRank.N,
  },
  [CardKind.AcidicSwampOoze]: {
    image: AcidicSwampOoze,
    cost: 2,
    name: 'Corruptor',
    hp: 2,
    attack: 3,
    trait: 0,
    canAttack: 0,
    needTarget: false,
    type: 'servant',
    class: HeroKind.None,
    rank: CardRank.N,
  },
  [CardKind.Nightblade]: {
    image: Nightblade,
    cost: 5,
    name: 'Nightfall Sovereign',
    hp: 4,
    attack: 4,
    trait: 0,
    canAttack: 0,
    needTarget: false,
    type: 'servant',
    class: HeroKind.None,
    rank: CardRank.N,
  },
  [CardKind.EarthenRingFarseer]: {
    image: EarthenRingFarseer,
    cost: 3,
    name: 'Forest Font',
    hp: 3,
    attack: 3,
    trait: 0,
    canAttack: 0,
    needTarget: true,
    type: 'servant',
    class: HeroKind.None,
    rank: CardRank.N,
  },
  [CardKind.VoodooDoctor]: {
    image: VoodooDoctor,
    cost: 1,
    name: 'Hexer',
    hp: 1,
    attack: 2,
    trait: 0,
    canAttack: 0,
    needTarget: true,
    type: 'servant',
    class: HeroKind.None,
    rank: CardRank.N,
  },
  [CardKind.ShatteredSunCleric]: {
    image: ShatteredSunCleric,
    cost: 3,
    name: 'Energetic Crystal',
    hp: 2,
    attack: 3,
    trait: 0,
    canAttack: 0,
    needTarget: true,
    type: 'servant',
    class: HeroKind.None,
    rank: CardRank.N,
  },
  [CardKind.PriestessOfElune]: {
    image: PriestessOfElune,
    cost: 6,
    name: 'Priestess',
    hp: 4,
    attack: 5,
    trait: 0,
    canAttack: 0,
    needTarget: false,
    type: 'servant',
    class: HeroKind.None,
    rank: CardRank.N,
  },
  [CardKind.DarkscaleHealer]: {
    image: DarkscaleHealer,
    cost: 5,
    name: 'Healing Touch',
    hp: 5,
    attack: 4,
    trait: 0,
    canAttack: 0,
    needTarget: false,
    type: 'servant',
    class: HeroKind.None,
    rank: CardRank.N,
  },
  [CardKind.DarkIronDwarf]: {
    image: DarkIronDwarf,
    cost: 4,
    name: 'Arcane Anomaly',
    hp: 4,
    attack: 4,
    trait: 0,
    canAttack: 0,
    needTarget: true,
    type: 'servant',
    class: HeroKind.None,
    rank: CardRank.N,
  },
  [CardKind.ElvenArcher]: {
    image: ElvenArcher,
    cost: 1,
    name: 'Explosive Crossbowman',
    hp: 1,
    attack: 1,
    trait: 0,
    canAttack: 0,
    needTarget: true,
    type: 'servant',
    class: HeroKind.None,
    rank: CardRank.N,
  },
  [CardKind.FrostwolfWarlord]: {
    image: FrostwolfWarlord,
    cost: 5,
    name: 'Frostwind Direwolf',
    hp: 4,
    attack: 4,
    trait: 0,
    canAttack: 0,
    needTarget: false,
    type: 'servant',
    class: HeroKind.None,
    rank: CardRank.R,
  },
  [CardKind.Gorehowl]: {
    image: Gorehowl,
    cost: 3,
    name: 'Bloodthirst',
    hp: 1,
    attack: 7,
    trait: 0,
    canAttack: 0,
    needTarget: false,
    type: 'weapon',
    class: HeroKind.Warrior,
    rank: CardRank.SR,
  },
}
